#include "reset_presenter.h"
#include <assert.h>
#include <stdio.h>
#include <string.h>
int main(void) {
    _Static_assert(RESET_UI_HOME == 0 && RESET_UI_OVERVIEW == 1 && RESET_UI_STATS == 2 && RESET_UI_SETTINGS == 3, "four top pages");
    reset_feed_snapshot_t f = {0};
    reset_presenter_state_t s = {.battery = -1, .now = 1791000000};
    reset_settings_defaults(&s.settings);
    reset_ui_model_t m;
    reset_presenter_build(&f, &s, &m);
    assert(!strcmp(m.hero, "--") && !strcmp(m.battery, ""));
    assert(m.warning && strstr(m.freshness, "配网"));
    assert(strstr(m.next_body, "暂未公布") && strstr(m.announcement_type, "暂无"));
    s.connected = s.clock_ready = true; s.battery = 75;
    f.has_data = true; f.status = RESET_FEED_CURRENT; f.last_checked_at = s.now;
    f.data.generated_at = s.now; f.data.latest.present = true;
    f.data.latest.kind = RESET_KIND_REGULAR; f.data.latest.announced_at = s.now - 118800;
    strcpy(f.data.latest.text, "Original latest text.");
    f.data.stats.total = 57; f.data.stats.has_avg_interval_days = true; f.data.stats.avg_interval_days = 6.8;
    reset_presenter_build(&f, &s, &m);
    assert(!strcmp(m.hero, "1天9小时前") && !strcmp(m.battery, "75%"));
    assert(!strcmp(m.stats_total, "57") && !strcmp(m.stats_average, "6.8"));
    assert(!strcmp(m.stats_elapsed, "--") && !m.has_notice);
    assert(!strcmp(m.announcement_text, f.data.latest.text));
    assert(strstr(m.status, "CODEX") && strstr(m.announcement_type, "已执行"));
    /* A newer prediction is never an announcement or an inferred schedule. */
    f.data.watch.present = true; f.data.watch.observed_at = s.now;
    f.data.watch.expires_at = s.now + 3600;
    strcpy(f.data.watch.forecast_window, "within the next few hours");
    reset_presenter_build(&f, &s, &m);
    assert(!strcmp(m.announcement_text, f.data.latest.text));
    assert(!strcmp(m.next_body, f.data.watch.forecast_window) && strstr(m.next_title, "预测"));
    f.data.watch.expires_at = s.now;
    reset_presenter_build(&f, &s, &m);
    assert(!m.has_notice && strstr(m.next_body, "已过期") && strstr(m.next_body, "暂未公布"));
    f.data.scheduled.present = f.data.scheduled.has_time = true;
    f.data.scheduled.scheduled_for = s.now - 1;
    f.data.scheduled.announced_at = s.now - 60;
    strcpy(f.data.scheduled.text, "Original scheduled text.");
    reset_presenter_build(&f, &s, &m);
    assert(m.has_notice && strstr(m.next_body, "等待确认") && strstr(m.next_body, "计划"));
    assert(!strcmp(m.announcement_text, f.data.scheduled.text) && strstr(m.announcement_type, "已计划"));
    assert(!strcmp(m.hero, "1天9小时前")); /* Last executed overview stays independent. */
    f.data.scheduled.kind = RESET_KIND_BANKED;
    reset_presenter_build(&f, &s, &m);
    assert(strstr(m.announcement_type, "备用额度") && strstr(m.announcement_type, "已计划"));
    f.data.scheduled.has_time = false;
    reset_presenter_build(&f, &s, &m); assert(strstr(m.next_body, "待定"));
    f.data.scheduled.announced_at = f.data.latest.announced_at;
    reset_presenter_build(&f, &s, &m); assert(!strcmp(m.announcement_text, f.data.latest.text));
    f.data.scheduled.announced_at--;
    reset_presenter_build(&f, &s, &m); assert(!strcmp(m.announcement_text, f.data.latest.text));
    f.data.latest.present = false;
    reset_presenter_build(&f, &s, &m); assert(!strcmp(m.announcement_text, f.data.scheduled.text) && !strcmp(m.hero, "--"));
    f.data.latest.present = true; f.data.scheduled.present = false;
    f.data.latest.kind = RESET_KIND_BANKED; f.data.latest.observed = true;
    f.data.latest.text_truncated = true;
    reset_presenter_build(&f, &s, &m);
    assert(strstr(m.status, "备用额度发放") && strstr(m.detail_source, "观察") && m.announcement_truncated);
    s.settings.wifi_enabled = false; s.radio_control_pending = true;
    reset_presenter_build(&f, &s, &m); assert(strstr(m.freshness, "正在关闭"));
    s.radio_control_pending = false;
    reset_presenter_build(&f, &s, &m); assert(strstr(m.freshness, "关闭失败") && strstr(m.settings_values[0], "失败"));
    s.radio_stopped = true;
    reset_presenter_build(&f, &s, &m); assert(strstr(m.freshness, "已关闭"));
    s.settings.wifi_enabled = true; s.refresh_throttled = true; f.retry_in_seconds = 29;
    reset_presenter_build(&f, &s, &m); assert(strstr(m.freshness, "29 秒"));
    f.data.latest.announced_at = 1790982000; /* 2026-10-02 23:00 UTC */
    s.settings.utc_offset_minutes = 120;
    reset_presenter_build(&f, &s, &m); assert(!strcmp(m.date, "2026-10-03 01:00") && !strcmp(m.zone, "UTC+02:00"));
    s.settings.utc_offset_minutes = -420;
    reset_presenter_build(&f, &s, &m); assert(!strcmp(m.date, "2026-10-02 16:00") && !strcmp(m.zone, "UTC-07:00"));
    s.page = RESET_UI_TIMEZONE; s.draft_utc_offset = 345;
    reset_presenter_build(&f, &s, &m); assert(!strcmp(m.zone, "UTC+05:45"));
    s.page = RESET_UI_HOME; s.settings.sleep_minutes = 30;
    reset_presenter_build(&f, &s, &m); assert(!strcmp(m.settings_values[4], "30 分钟"));
    s.settings.sleep_minutes = 0;
    reset_presenter_build(&f, &s, &m); assert(!strcmp(m.settings_values[4], "关闭"));
    assert(!strcmp(m.settings_values[5], "进入") && !strcmp(m.settings_values[6], "返回"));
    f.data.latest.announced_at = s.now - 20;
    reset_presenter_build(&f, &s, &m); assert(!strcmp(m.hero, "刚刚"));
    f.data.latest.announced_at = s.now + 1;
    reset_presenter_build(&f, &s, &m); assert(!strcmp(m.hero, "时间待核对"));
    s.clock_ready = false;
    f.data.watch.expires_at = s.now + 3600;
    reset_presenter_build(&f, &s, &m); assert(!m.timing_is_forecast && strstr(m.next_body, "待校时"));
    s.reading_page = 1000;
    reset_presenter_build(&f, &s, &m); assert(m.reading_page == 7);
    /* Setup diagnostics do not reveal an SSID/password or infer persistence
     * from an IP. Firmware fields are deliberately independent. */
    s.page = RESET_UI_SETUP; s.provisioning = false; s.connected = false;
    s.settings.wifi_enabled = true; s.wifi_initialized = false;
    s.wifi_last_error = 0; s.wifi_persistence_error = 0;
    reset_presenter_build(&f, &s, &m);
    assert(strstr(m.setup_line, "正在启动") && !strcmp(m.settings_values[0], "启动中"));
    s.wifi_last_error = INT32_MIN;
    reset_presenter_build(&f, &s, &m);
    assert(strstr(m.setup_line, "启动失败") && strstr(m.setup_timer, "-2147483648"));
    s.wifi_initialized = true; s.wifi_last_error = 0; s.has_credentials = false;
    reset_presenter_build(&f, &s, &m); assert(strstr(m.setup_line, "未保存网络") && !strcmp(m.settings_values[0], "未配网"));
    s.has_credentials = true; s.wifi_connecting = true; s.wifi_attempts = 3;
    reset_presenter_build(&f, &s, &m); assert(strstr(m.setup_line, "3/5") && !strcmp(m.settings_values[0], "连接中"));
    s.wifi_connecting = false; s.wifi_attempts = 5; s.wifi_disconnect_reason = UINT16_MAX;
    s.wifi_last_error = INT32_MAX;
    reset_presenter_build(&f, &s, &m);
    assert(strstr(m.setup_line, "等待重试") && strstr(m.setup_timer, "2147483647") && strstr(m.setup_timer, "65535"));
    s.connected = true; s.wifi_persistence_error = INT32_MIN;
    reset_presenter_build(&f, &s, &m);
    assert(strstr(m.setup_line, "凭证保存失败") && strstr(m.settings_values[0], "未保存"));
    assert(strstr(m.setup_timer, "2147483647") && strstr(m.setup_diagnostic, "-2147483648"));
    s.provisioning = true; s.provisioning_seconds = 180;
    reset_presenter_build(&f, &s, &m);
    assert(strstr(m.setup_timer, "180 秒") && strstr(m.setup_diagnostic, "-2147483648"));
    assert(strstr(m.setup_line, "凭证保存失败"));
    s.wifi_persistence_error = 0;
    reset_presenter_build(&f, &s, &m);
    assert(!m.setup_diagnostic[0] && strstr(m.setup_timer, "180 秒"));
    s.provisioning = false;
    reset_presenter_build(&f, &s, &m); assert(!strcmp(m.settings_values[0], "已连接"));
    puts("Reset presenter tests: PASS");
    return 0;
}
