#include "reset_presenter.h"
#include <assert.h>
#include <stdio.h>
#include <string.h>
int main(void) {
    _Static_assert(RESET_UI_HOME == 0 && RESET_UI_HISTORY == 1 && RESET_UI_STATS == 2 && RESET_UI_SETTINGS == 3 && RESET_UI_READING == 4, "four top pages plus child reader");
    reset_feed_data_t data = {0};
    reset_feed_snapshot_t f = {.data = &data, .revision = 1};
    reset_presenter_state_t s = {.battery = -1, .now = 1791000000};
    reset_settings_defaults(&s.settings);
    reset_ui_model_t m;
    reset_reader_snapshot_t saved = {.valid = true};
    reset_presenter_build(&f, &s, &m);
    assert(!m.reading_available && !m.primary_scheduled && !m.next_has_time);
    assert(!strcmp(m.hero, "--") && !strcmp(m.battery, ""));
    assert(!strcmp(m.next_time, "暂未公布") && m.warning && strstr(m.freshness, "配网"));
    assert(!reset_presenter_capture_reader(&m, &saved) && !saved.valid);
    assert(!reset_presenter_capture_reader(NULL, &saved));
    assert(!reset_presenter_capture_reader(&m, NULL));
    s.connected = s.clock_ready = true; s.battery = 75;
    f.has_data = true; f.status = RESET_FEED_CURRENT; f.last_checked_at = s.now;
    data.generated_at = s.now; data.latest.present = true;
    data.latest.kind = RESET_KIND_REGULAR; data.latest.announced_at = s.now - 118800;
    strcpy(data.latest.text, "Original latest text.");
    strcpy(data.latest.source_url, "https://x.com/test/status/1");
    data.stats.total = 57; data.stats.has_avg_interval_days = true; data.stats.avg_interval_days = 6.8;
    reset_presenter_build(&f, &s, &m);
    assert(m.reading_available && !m.primary_scheduled && !m.next_has_time);
    assert(!strcmp(m.next_title, "最近一次重置") && !strcmp(m.hero, "1天9小时前"));
    assert(!strcmp(m.stats_total, "57") && !strcmp(m.stats_average, "6.8"));
    assert(!strcmp(m.announcement_text, data.latest.text) && strstr(m.announcement_type, "已执行"));
    assert(m.announcement_source_original && !strcmp(m.announcement_source_url, data.latest.source_url));
    /* A newer watch is strictly secondary, never the reader selection. */
    data.watch.present = true; data.watch.observed_at = s.now;
    data.watch.expires_at = s.now + 3600; data.watch.confidence_percent = 87;
    strcpy(data.watch.forecast_window, "within the next few hours");
    reset_presenter_build(&f, &s, &m);
    assert(m.timing_is_forecast && m.forecast_confidence == 87);
    assert(!strcmp(m.announcement_text, data.latest.text) && !strcmp(m.next_body, data.watch.forecast_window));
    assert(!m.primary_scheduled && !m.next_has_time && !strcmp(m.hero, "1天9小时前"));
    data.watch.expires_at = s.now;
    reset_presenter_build(&f, &s, &m); assert(!m.timing_is_forecast && !m.next_body[0]);
    data.watch.expires_at = s.now + 3600; s.clock_ready = false;
    reset_presenter_build(&f, &s, &m); assert(!m.timing_is_forecast);
    s.clock_ready = true;
    /* A scheduled record wins even when its announcement is OLDER. */
    data.scheduled.present = data.scheduled.has_time = true;
    data.scheduled.kind = RESET_KIND_REGULAR;
    data.scheduled.announced_at = data.latest.announced_at - 3600;
    data.scheduled.scheduled_for = s.now + 7200;
    strcpy(data.scheduled.text, "Original planned reset text.");
    strcpy(data.scheduled.source_url, "https://twitter.com/test/status/2");
    reset_presenter_build(&f, &s, &m);
    assert(m.primary_scheduled && m.next_has_time && m.reading_available);
    assert(!strcmp(m.next_title, "下一次重置") && !strcmp(m.next_time, "06:00") && !strcmp(m.next_date, "2026-10-03"));
    assert(!strcmp(m.announcement_text, data.scheduled.text) && !strcmp(m.announcement_source_url, data.scheduled.source_url));
    assert(strstr(m.next_status, "已计划") && m.timing_is_forecast);
    /* Null remains unpublished; an expired planned time never means executed. */
    data.scheduled.has_time = false;
    reset_presenter_build(&f, &s, &m);
    assert(!m.next_has_time && !strcmp(m.next_time, "暂未公布") && m.primary_scheduled);
    data.scheduled.has_time = true; data.scheduled.scheduled_for = s.now - 60;
    reset_presenter_build(&f, &s, &m);
    assert(strstr(m.next_status, "等待确认") && !strstr(m.next_status, "已执行"));
    data.scheduled.kind = RESET_KIND_BANKED;
    reset_presenter_build(&f, &s, &m); assert(strstr(m.announcement_type, "备用额度"));
    data.scheduled.scheduled_for = 1790982000; /* 2026-10-02 23:00 UTC */
    s.settings.utc_offset_minutes = 120;
    data.scheduled.text_truncated = true;
    reset_presenter_build(&f, &s, &m);
    assert(!strcmp(m.next_date, "2026-10-03") && !strcmp(m.next_time, "01:00") && !strcmp(m.zone, "UTC+02:00"));
    assert(reset_presenter_capture_reader(&m, &saved) && saved.valid);
    assert(m.announcement_text == data.scheduled.text && saved.text == m.announcement_text);
    assert(saved.revision == f.revision); /* No original-text copy in either view. */
    assert(saved.truncated && saved.source_original);
    /* The open reader keeps all of its event fields through source replacement,
     * timezone change, expiry and even complete loss of live feed data. */
    s.page = RESET_UI_READING; s.reader_snapshot = &saved; s.reading_page = 8;
    data.scheduled.present = false;
    strcpy(data.latest.text, "A new live record must not replace the open one.");
    strcpy(data.latest.source_url, "https://x.com/test/status/3");
    s.settings.utc_offset_minutes = -420; s.now += 86400;
    reset_presenter_build(&f, &s, &m);
    assert(m.reading_available && m.reading_page == 8 && !strcmp(m.announcement_text, saved.text));
    assert(!strcmp(m.announcement_type, saved.type) && !strcmp(m.announcement_date, saved.date));
    assert(!strcmp(m.zone, saved.zone) && !strcmp(m.announcement_source_url, saved.source_url));
    assert(m.announcement_truncated == saved.truncated && m.announcement_source_original == saved.source_original);
    f.has_data = false;
    reset_presenter_build(&f, &s, &m); assert(m.reading_available && !strcmp(m.announcement_text, saved.text));
    f.has_data = true; s.reader_snapshot = NULL;
    reset_presenter_build(&f, &s, &m);
    assert(!m.reading_available && strcmp(m.announcement_text, data.latest.text));
    assert(!strcmp(m.announcement_source_url, "https://codex-resets.com/zh-CN"));
    s.reader_snapshot = &saved; saved.valid = false;
    reset_presenter_build(&f, &s, &m); assert(!m.reading_available);
    s.page = RESET_UI_HOME; s.reader_snapshot = NULL;
    data.latest.observed = true; data.latest.kind = RESET_KIND_BANKED;
    reset_presenter_build(&f, &s, &m);
    assert(!m.primary_scheduled && m.reading_available && strstr(m.next_title, "备用额度"));
    assert(!m.announcement_source_original && !strcmp(m.announcement_source_url, "https://codex-resets.com/zh-CN"));
    data.latest.observed = false; data.latest.source_url[0] = '\0';
    reset_presenter_build(&f, &s, &m); assert(!m.announcement_source_original);
    data.latest.present = false; data.watch.expires_at = s.now + 3600;
    reset_presenter_build(&f, &s, &m);
    assert(m.timing_is_forecast && !m.reading_available && !m.primary_scheduled && !m.next_has_time);
    assert(!strcmp(m.next_time, "暂未公布")); /* Historical averages cannot become a plan. */
    s.page = RESET_UI_STATS;
    reset_presenter_build(&f, &s, &m); assert(!m.reading_available);
    s.page = RESET_UI_SETTINGS;
    reset_presenter_build(&f, &s, &m); assert(!m.reading_available);
    s.settings.sleep_minutes = 30;
    reset_presenter_build(&f, &s, &m); assert(!strcmp(m.settings_values[4], "30 分钟"));
    s.settings.sleep_minutes = 0;
    reset_presenter_build(&f, &s, &m); assert(!strcmp(m.settings_values[4], "关闭"));
    s.page = RESET_UI_TIMEZONE; s.draft_utc_offset = 345;
    reset_presenter_build(&f, &s, &m); assert(!strcmp(m.zone, "UTC+05:45"));
    s.page = RESET_UI_HOME; data.latest.present = true;
    data.latest.announced_at = s.now - 20;
    reset_presenter_build(&f, &s, &m); assert(!strcmp(m.hero, "刚刚"));
    data.latest.announced_at = s.now + 1;
    reset_presenter_build(&f, &s, &m); assert(!strcmp(m.hero, "时间待核对"));
    s.settings.wifi_enabled = false; s.radio_control_pending = true;
    reset_presenter_build(&f, &s, &m); assert(strstr(m.freshness, "正在关闭"));
    s.radio_control_pending = false; s.radio_stopped = true;
    reset_presenter_build(&f, &s, &m); assert(strstr(m.freshness, "已关闭"));
    s.settings.wifi_enabled = true; s.refresh_throttled = true; f.retry_in_seconds = 29;
    reset_presenter_build(&f, &s, &m); assert(strstr(m.freshness, "29 秒"));
    /* Calendar UTC and coverage semantics are independent of local offset. */
    reset_history_snapshot_t history = {.has_data = true, .status = RESET_FEED_CURRENT};
    s.page = RESET_UI_HISTORY; s.clock_ready = true;
    history.data.start_day = reset_history_window_start(s.now);
    history.data.through_at = s.now;
    memset(history.data.cells, RESET_HISTORY_KNOWN, sizeof(history.data.cells));
    history.data.cells[1] |= RESET_HISTORY_REGULAR;
    history.data.cells[2] |= RESET_HISTORY_BANKED;
    history.data.cells[3] |= RESET_HISTORY_REGULAR | RESET_HISTORY_BANKED;
    history.data.cells[4] = 0;
    s.history = &history;
    reset_presenter_build(&f, &s, &m);
    assert(!m.reading_available && m.history_cells[0] == RESET_HISTORY_DAY_EMPTY);
    assert(m.history_cells[1] == RESET_HISTORY_DAY_REGULAR && m.history_cells[2] == RESET_HISTORY_DAY_BANKED);
    assert(m.history_cells[3] == RESET_HISTORY_DAY_BOTH && m.history_cells[4] == RESET_HISTORY_DAY_UNKNOWN);
    assert(strstr(m.history_note, "部分未知"));
    char utc_range[48]; snprintf(utc_range, sizeof(utc_range), "%s", m.history_range);
    s.settings.utc_offset_minutes = 840;
    reset_presenter_build(&f, &s, &m); assert(!strcmp(m.history_range, utc_range));
    history.has_data = false; history.status = RESET_FEED_ERROR;
    reset_presenter_build(&f, &s, &m); assert(m.history_cells[0] == RESET_HISTORY_DAY_UNKNOWN && strstr(m.history_note, "读取失败"));
    history.has_data = true; history.loading = true;
    reset_presenter_build(&f, &s, &m); assert(m.history_cells[1] == RESET_HISTORY_DAY_REGULAR && strstr(m.history_note, "读取中"));
    history.status = RESET_FEED_WAITING_WIFI;
    reset_presenter_build(&f, &s, &m); assert(strstr(m.history_note, "等待联网"));
    history.status = RESET_FEED_WAITING_CLOCK;
    reset_presenter_build(&f, &s, &m); assert(strstr(m.history_note, "等待校时"));
    history.loading = false; history.status = RESET_FEED_CURRENT;
    s.now = history.data.start_day + (RESET_HISTORY_DAYS - 4) * INT64_C(86400) + 3600;
    reset_presenter_build(&f, &s, &m); assert(m.history_cells[RESET_HISTORY_DAYS - 1] == RESET_HISTORY_DAY_FUTURE);
    s.clock_ready = false; s.restored_cache = false;
    reset_presenter_build(&f, &s, &m); assert(m.history_cells[0] == RESET_HISTORY_DAY_UNKNOWN && strstr(m.history_note, "等待校时"));
    s.history = NULL; s.clock_ready = true;
    /* Setup diagnostics do not reveal an SSID/password or infer persistence
     * from an IP. Firmware fields are deliberately independent. */
    s.page = RESET_UI_SETUP; s.provisioning = false; s.connected = false;
    s.settings.wifi_enabled = true; s.wifi_initialized = false;
    s.wifi_last_error = 0; s.wifi_persistence_error = 0;
    reset_presenter_build(&f, &s, &m);
    assert(strstr(m.setup_line, "正在启动") && !strcmp(m.settings_values[0], "启动中"));
    s.wifi_last_error = INT32_MIN;
    reset_presenter_build(&f, &s, &m);
    assert(strstr(m.setup_line, "启动失败") && strstr(m.setup_timer, "-2147483648"));
    s.wifi_initialized = true; s.wifi_last_error = 0; s.has_credentials = false;
    reset_presenter_build(&f, &s, &m); assert(strstr(m.setup_line, "未保存网络") && !strcmp(m.settings_values[0], "未配网"));
    s.has_credentials = true; s.wifi_connecting = true; s.wifi_attempts = 3;
    reset_presenter_build(&f, &s, &m); assert(strstr(m.setup_line, "3/5") && !strcmp(m.settings_values[0], "连接中"));
    s.wifi_connecting = false; s.wifi_attempts = 5; s.wifi_disconnect_reason = UINT16_MAX;
    s.wifi_last_error = INT32_MAX;
    reset_presenter_build(&f, &s, &m);
    assert(strstr(m.setup_line, "等待重试") && strstr(m.setup_timer, "2147483647") && strstr(m.setup_timer, "65535"));
    s.connected = true; s.wifi_persistence_error = INT32_MIN;
    reset_presenter_build(&f, &s, &m);
    assert(strstr(m.setup_line, "凭证保存失败") && strstr(m.settings_values[0], "未保存"));
    assert(strstr(m.setup_timer, "2147483647") && strstr(m.setup_diagnostic, "-2147483648"));
    s.provisioning = true; s.provisioning_seconds = 180;
    reset_presenter_build(&f, &s, &m);
    assert(strstr(m.setup_timer, "180 秒") && strstr(m.setup_diagnostic, "-2147483648"));
    assert(strstr(m.setup_line, "凭证保存失败"));
    s.wifi_persistence_error = 0;
    reset_presenter_build(&f, &s, &m);
    assert(!m.setup_diagnostic[0] && strstr(m.setup_timer, "180 秒"));
    s.provisioning = false;
    reset_presenter_build(&f, &s, &m); assert(!strcmp(m.settings_values[0], "已连接"));
    puts("Reset presenter tests: PASS");
    return 0;
}
